project:
  type: website
  output-dir: docs

website:
  title: "Álgebra Linear"
  site-url: https://raphateixeira.github.io/AlgebraLinear/
  repo-url: https://github.com/raphateixeira/AlgebraLinear
  
format:
  html:
    theme: [cosmo, TemaRTx.scss]
    lang: pt-BR
  revealjs:
    theme: [default, TemaRTx.scss]
    lang: pt-BR
    width: 1600
    height: 900