project:
  type: website
  output-dir: docs

website:
  title: "Álgebra Linear"
  site-url: https://raphateixeira.github.io/AlgebraLinear/
  repo-url: https://github.com/raphateixeira/AlgebraLinear
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Início
      - section: "Notas de Aula"
        contents:
          - href: Notas/AL01SistemasEquacoes.html
            text: "Aula 01: Sistemas de Equações Lineares"
          - href: Notas/AL02MatrizesOperacoes.html
            text: "Aula 02: Matrizes e Operações Matriciais"


format:
  html:
    theme: default
    lang: pt-BR
    scss: TemaRTx.scss
    toc: true
    code-copy: true
    
  revealjs:
    theme: default
    scss: TemaRTx.scss
    transition: slide
    slide-number: true
    footer: "Álgebra Linear - Prof. Raphael Teixeira"
    width: 1600
    height: 900
    code-theme: monokai
    code-font-size: 2.0em
    code-line-numbers: true