name: Render and Publish

on:
  push:
    branches: [ main ] # Se sua branch principal for 'master', troque 'main' por 'master'

# Permissões necessárias para que o GitHub Actions publique no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Instalação de Python ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install jupyter numpy scipy matplotlib

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Deve ser exatamente igual ao output-dir do seu _quarto.yml
          path: docs 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4